### ISSUE TITLE
Toggles don't save with Charge installed

### ISSUE THREAD

**Issue by 1stevengrant** [edalzell/statamic-charge#16]
Noticed today that when Charge is installed, an unrelated `toggle` field in our `blog.yaml` fieldset won't persist the change.

Removed all addons and installed individually to track down.

**Comment by 1stevengrant** [comment]
```
sections:
  main:
    display: Main
    fields:
      featured_post:
        type: toggle
        display: Featured Post
      blog_image:
        type: assets
        container: s3_container
        folder: /
        max_files: 1
        validate: required
        display: Blog Image
        instructions: Choose a good image for the post
      summary:
        type: textarea
        display: Summary
        instructions: Give an overview of the post
      author:
        instructions: Who wrote this piece?
        type: collection
        collection:
          - people
        display: Author
      body:
        type: partial
        fieldset: page_builder
        display: Body
  tags_and_categories:
    display: 'Tags & Categories'
    fields:
      categories:
        type: taxonomy
        taxonomy: categories
        display: Categories
      tags:
        type: taxonomy
        taxonomy: tags
        display: Tags
  legacy_content:
    display: Legacy Content
    fields:
      blog_content:
        display: Blog Content
        type: redactor
  misc:
    display: Misc
    fields:
      impressions:
        type: text
        display: Impressions
      legacy_id:
        type: text
        display: Legacy ID
      meta_description:
        type: textarea
        display: Meta Description
taxonomies: false
title: Blog Post
create_title: Blog Post
```
