### ISSUE TITLE
Error when changing user roles

### ISSUE THREAD

**Issue by jeremydouglas** [edalzell/statamic-charge#37]
I'm getting this error when a user subscribes and user roles are set:

```
[2020-01-05 21:16:59] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /Users/jeremyhoover/Sites/deboss-garage-api/public/site/addons/Charge/Actions/UpdateUserRolesAction.php:9
```

If it helps, this is what I'm using as a charge config file:
```
currency: usd
active: Active
canceling: Canceling
past_due: 'Past Due'
canceled: Canceled
plans_and_roles:
  -
    plan: plan_GCmdg3U0GEib2B
    role:
      - 93b31b39-47af-4bd2-83ca-100b39eca84f
canceled_email_template: email/cancel_subscription
payment_failed_email_template: email/payment_failed
upcoming_payment_email_template: email/payment_upcoming
charge_formset: subscribe
```
