### ISSUE TITLE
E-mail template settings are gone

### ISSUE THREAD

**Issue by studio1902** [edalzell/statamic-charge#58]
The email template settings are gone from the CP. It's unclear for users a.t.m. how they can specify this or which ones get used.

**Comment by edalzell** [comment]
They are there for me @studio1902 what do you see?

<img width="978" alt="image" src="https://user-images.githubusercontent.com/6069653/73115688-610b1700-3ede-11ea-9f0f-3a2dde5ce957.png">

**Comment by studio1902** [comment]
<img width="1169" alt="Screenshot 2020-01-26 at 12 13 51" src="https://user-images.githubusercontent.com/4067523/73134305-5f079c00-4035-11ea-9a52-f4ddb1334461.png">

**Comment by studio1902** [comment]
What I already tried is: downloading latest version, update:addons, clear:stache, clear:cache. All to no avail.

**Comment by edalzell** [comment]
let's see your `charge.yaml` settings file.

**Comment by studio1902** [comment]
```
currency: eur
active: Active
canceling: Canceling
past_due: 'Past Due'
canceled: Canceled
plans_and_roles:
  -
    plan: plan_GVgw2VYIHEq1dO
    prorate: true
    role:
      - 95f9496f-361f-4cda-b97d-a50cb2f57da6
from_email: noreply@site.com
canceled_email_template: email/charge_canceled_payment
payment_failed_email_template: email/charge_failed_payment
upcoming_payment_email_template: email/charge_upcoming_payment
```
